// @system — product identity config (template defaults)
// DO NOT edit this file for product-specific values — use @custom/info.js instead.
// This file is overwritten during template sync.
export const info = {
  name: 'ProductTemplate',
  tagline: 'Your product tagline here',
  url: import.meta.env.VITE_APP_URL ?? 'http://localhost:5173',
  supportEmail: 'support@example.com',
}
