const express = require('express')
const router = express.Router()

router.use(require('../../api/@system/ping'))
router.use(require('../../api/@system/health'))
router.use(require('../../api/@system/csrf'))
router.use(require('../../api/@system/auth'))
router.use(require('../../api/@system/sessions'))
router.use(require('../../api/@system/user'))
router.use(require('../../api/@system/totp'))
router.use(require('../../api/@system/admin'))
router.use(require('../../api/@system/stripe'))
router.use(require('../../api/@system/polar'))
router.use(require('../../api/@system/subscriptions'))
router.use(require('../../api/@system/payments'))
router.use(require('../../api/@system/api-keys'))
router.use(require('../../api/@system/oauth'))
router.use(require('../../api/@system/onboarding'))
router.use(require('../../api/@system/email'))
router.use(require('../../api/@system/ai'))
router.use(require('../../api/@system/integrations'))
router.use(require('../../api/@system/storage'))
router.use(require('../../api/@system/search'))
router.use(require('../../api/@system/brands'))
router.use(require('../../api/@system/teams/router'))
router.use(require('../../api/@system/usage'))

module.exports = router
